@startuml classes
class Restaurant {
   id Integer 
   name String
   menus Array<menu>
   ---   
   addMenu(<menu>)
   removeMenu(<menu>)
}
class Menu {
    id Integer
    title String
    items Array<item>
    ---
    addItem(<item>)
    deleteItem(<item>)

}
class Item {
    id Integer
    description String
    price Number
    ---
    createItem(description, price)
    deleteItem(<item>)
}

Restaurant --{ Menu 
Menu --{ Item

@enduml